// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRYTYtTuFEwZdf7QDjGu5nJa2hylHKgEM',
    appId: '1:760846035526:web:84fd3b3bd11c1576ba7847',
    messagingSenderId: '760846035526',
    projectId: 'agritech-ac407',
    authDomain: 'agritech-ac407.firebaseapp.com',
    databaseURL: 'https://agritech-ac407-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agritech-ac407.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDHkRPVjWa5myqcfHYF8MVc9Oq_Y63hU4',
    appId: '1:760846035526:android:0fe8fe730315d536ba7847',
    messagingSenderId: '760846035526',
    projectId: 'agritech-ac407',
    databaseURL: 'https://agritech-ac407-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agritech-ac407.firebasestorage.app',
  );

}